#/**********************
#* Luke Brown          *
#* luke4@g.clemson.edu *
#* Section 003         *
#* Lab 9               *
#* 10-18-16            *
#**********************/
Money: money.cpp driver.cpp
	g++ -Wall money.cpp driver.cpp -o money
run: Money
	./money
clean:
	rm money
	rm *.o
